twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    # Global custom variables
    globals:
        globalMediaTextError: 'Media loading Error'
